### ISSUE TITLE
Not open no perm?

### ISSUE THREAD

**Issue by Root-didi** [AnykeysTTV/pg-admin#2]

**Comment by markbucko12341** [comment]
same issue im having .. menu not opening when doing /adminmenu  -_-

**Comment by AnykeysTTV** [comment]
Might be because i have been running an older or newer version of qbcore my exusses

**Comment by markbucko12341** [comment]
im running the latest qbcore .. even if i was using a older version il should get errors lol 
.. how do you set your self as admin  .. i mite be doing it wrong  ?

**Comment by AnykeysTTV** [comment]
add_principal identifier.license{your key} qbcore.god

**Comment by markbucko12341** [comment]
yea thats what i have in the server.cfg .. and still nothing

**Comment by markbucko12341** [comment]
`#add_principal identifier.{{principalMasterIdentifier}} qbcore.god <- doesn't exist yet, change the generated one below to qbcore.god`

**Comment by AnykeysTTV** [comment]
Oke but have you made your self admin ? without the # ? can you use other commands like /giveitem ?

**Comment by markbucko12341** [comment]
yea im admin .. i can use qb-admin

**Comment by AnykeysTTV** [comment]
one moment let me double check

**Comment by AnykeysTTV** [comment]
works on my test server but i havent renamed pg- to qb-

**Comment by AnykeysTTV** [comment]
in your cl_main.lua did you have ` 
RegisterNetEvent('PGCore:Client:OnPlayerLoaded', function()
    Citizen.SetTimeout(1250, function()
        RefreshMenu('All')
        QBCore.Functions.TriggerCallback('mc-adminmenu/server/get-permission', function(PGroup)
            Group = PGroup
        end)
        exports['pg-admin']:CreateLog('Player Logged In', 'Player Logged In')
        LoggedIn = true
    end)
end)` renamed PGCore to your Core or QBCore ?

**Comment by markbucko12341** [comment]
this is what i have 
`RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
    Citizen.SetTimeout(1250, function()
        RefreshMenu('All')
        QBCore.Functions.TriggerCallback('mc-adminmenu/server/get-permission', function(PGroup)
            Group = PGroup
        end)
        exports['pg-admin']:CreateLog('Player Logged In', 'Player Logged In')
        LoggedIn = true
    end)
end)
`

**Comment by markbucko12341** [comment]
i have it working but getting this error  ? `script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: pg-admin was unable to execute a query!
[      script:oxmysql] Unknown column 'license' in 'field list'
[      script:oxmysql] INSERT INTO logs (Type, license, Log, Cid, Data) VALUES (?, ?, ?, ?, ?) ["Player Logged In","license:HIDDENIFO","Player Logged In","HIDDENIFO",null,null]
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:21766)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] > async rawQuery (@oxmysql/dist/build.js:21735)
[      script:oxmysql] `

**Comment by AnykeysTTV** [comment]
hey i am atm fixing everyhing on an fresh qb-core install give me 30 minutes

**Comment by markbucko12341** [comment]
i have mine working .. just that error

**Comment by markbucko12341** [comment]
do you have a discord bro  ?

**Comment by AnykeysTTV** [comment]
I see your error i have an fix for it give me like 10 minutes

**Comment by AnykeysTTV** [comment]
The new SQL is up in the github

**Comment by TheMdogShow** [comment]
so to open this you do /adminmenu ? 
also is there any work needed or is it drag and drop then add sql ?

**Comment by markbucko12341** [comment]
i think thats just it il check it out and get back  :)

**Comment by AnykeysTTV** [comment]
You can find my discord in readme.md now. For everyone sorry i have not test it on clean install

**Comment by markbucko12341** [comment]
10000% working perfect  .. thank you sooo much bro  .. no errors and works first time

**Comment by AnykeysTTV** [comment]
nice ! when you restart the script make sure to go back to character screen /logout

**Comment by markbucko12341** [comment]
yea i found that out lol .. also you discord isnt in the readme lol

**Comment by AnykeysTTV** [comment]
The discord server is :)

**Comment by AnykeysTTV** [comment]
Closing the issue because its solved !
